config/routes.rb
Rails.application.routes.draw do
  
  devise_for :usuarios, path: 'u'
  devise_for :auditors, path: 'a'
  
  get 	'inicio/index'
  get 	'/usuarios-cidade/:cidade' =>'usuarios#usuarios_cidade'
  get 	'/usuarios-alta-receita' =>'usuarios#usuarios_alto_valor'

  root :to => "inicio#index" 

  resources :patrimonios
  resources :usuarios
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/auditor.rb
class Auditor < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/patrimonio.rb
class Patrimonio < ApplicationRecord

	belongs_to :usuario

	validates :nome_patrimonio, presence: true
	validates :tipo, presence: true
	validates :valor, presence: true

end

app/models/usuario.rb
class Usuario < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

#	devise :registerable, :confirmable

	has_many :patrimonios, inverse_of: :usuario

	accepts_nested_attributes_for :patrimonios, allow_destroy: true

#	validates :nome, presence: true
#	validates :sexo, presence: true
#	validates :idade, presence: true, 	numericality: {grater_than: 0, only_integer: true}
#	validates :endereco, presence: true
#	validates :cidade, presence: true

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/inicio_controller.rb
class InicioController < ApplicationController
  def index
  	if usuario_signed_in?
  		@current = current_usuario
  	elsif auditor_signed_in?
  		@current = current_auditor
  	end
  end
end

app/controllers/patrimonios_controller.rb
class PatrimoniosController < ApplicationController
  before_action :set_patrimonio, only: [:show, :edit, :update, :destroy]


  # GET /patrimonios
  # GET /patrimonios.json
  def index
    @patrimonios = Patrimonio.all
  end

  # GET /patrimonios/1
  # GET /patrimonios/1.json
  def show
  end

  # GET /patrimonios/new
  def new
    @patrimonio = Patrimonio.new
  end

  # GET /patrimonios/1/edit
  def edit
  end

  # POST /patrimonios
  # POST /patrimonios.json
  def create
    @patrimonio = Patrimonios.new(patrimonio_params)

    respond_to do |format|
      if @patrimonio.save
        puts "salvo"
        format.html { redirect_to @patrimonio, notice: 'Patrimonio was successfully created.' }
        format.json { render :show, status: :created, location: @patrimonio }
      else
        puts @patrimonio.errors.full_messages
        format.html { render :new }
        format.json { render json: @patrimonio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /patrimonios/1
  # PATCH/PUT /patrimonios/1.json
  def update
    respond_to do |format|
      if @patrimonio.update(patrimonio_params)
        format.html { redirect_to @patrimonio, notice: 'Patrimonio was successfully updated.' }
        format.json { render :show, status: :ok, location: @patrimonio }
      else
        format.html { render :edit }
        format.json { render json: @patrimonio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /patrimonios/1
  # DELETE /patrimonios/1.json
  def destroy
    @patrimonio.destroy
    respond_to do |format|
      format.html { redirect_to patrimonios_url, notice: 'Patrimonio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_patrimonio
      @patrimonio = Patrimonio.find(params[:id])
      #@usuario = Usuario.find(@patrimonio.usuario_id)
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def patrimonio_params
      params.require(:patrimonio).permit(:nome_patrimonio, :tipo, :valor, :usuario_id)
    end


end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:patrimonio_total, :show, :edit, :update, :destroy]
  before_action :authenticate_auditor!, except: [:edit, :show, :create, :update]
  before_action :authenticate_usuario!, only: [:edit, :create, :update]


  # GET /usuarios
  # GET /usuarios.json
  def index
    if params[:cidade].present?  
      @usuarios = Usuario.where(cidade: params[:cidade])  
    elsif params[:valor].present?
      @usuarios = Usuario.joins(:patrimonios).group("usuarios.id").having("SUM(patrimonios.valor) > ?", params[:valor])
    else
      @usuarios = Usuario.all
    end
  end


  #GET /usuarios-cidade/CIDADE
  def usuarios_cidade
    @usuarios = Usuario.where(cidade: params[:cidade])
    respond_to do |format| 
      format.html
      format.json {render json: @usuarios.to_json(:include => :patrimonios)}
    end
  end


  #GET /usuarios-alta-receita/
  def usuarios_alto_valor
    @usuarios = Usuario.joins(:patrimonios).group("usuarios.id").having("SUM(patrimonios.valor) > 100000")
    respond_to do |format| 
      format.html
      format.json {render json: @usuarios.to_json(:include => :patrimonios)}
    end
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
    @usuario.patrimonios.build
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nome, :sexo, :idade, :endereco, :cidade, :patrimonios_attributes => [:id, :nome_patrimonio, :tipo, :valor, :_destroy])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/inicio_helper.rb
module InicioHelper
end

app/helpers/patrimonios_helper.rb
module PatrimoniosHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/inicio/index.html.erb
<div class= "page-header">
	<h1>Teste Receita Vice Governadoria</h1>
</div>
	
<h2>Cadastro de Cidadões e patrimonios.</h2>

<p id="notice"><%= notice %></p>


<%if auditor_signed_in?%>
	<ul>
		<li>Logado como Auditor</li>
		<li><%= current_auditor.email%></li>
		<li><%= link_to "Sair",  destroy_auditor_session_path, method: :delete %></li>
	</ul>

<%elsif usuario_signed_in?%>
	<ul>
		<li>Logado como Cidadão</li>
		<li><%= current_usuario.email%></li>
		<li><%= link_to "Sair",  destroy_usuario_session_path, method: :delete %></li>
	</ul>
<%else%>
	<ul>
		<li><%= link_to "Cadastrar novo Auditor",  new_auditor_registration_path %></li>
		<li><%= link_to "Cadastrar novo Cidadão",  new_usuario_registration_path %></li>
		<li><%= link_to "Logar como Auditor",  auditor_session_path %></li>
		<li><%= link_to "Logar como Cidadão",  usuario_session_path %></li>
	</ul>
<%end%>


<ul>
<%if usuario_signed_in?%>
	<li> <%= link_to "Perfil", usuario_path(@current.id)%> </li>
<%elsif auditor_signed_in? %>
	<li> <%= link_to "Usuarios", usuarios_path%> </li>
	<li> <%= link_to "Patrimonios", patrimonios_path%> </li><%end%>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReceitaVicegov</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/patrimonios/_form.html.erb
<%= form_for(patrimonio) do |f| %>
  <% if patrimonio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(patrimonio.errors.count, "error") %> prohibited this patrimonio from being saved:</h2>

      <ul>
      <% patrimonio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome_patrimonio %>
    <%= f.text_field :nome_patrimonio %>
  </div>

  <div class="field">
    <%= f.label :tipo %>
    <%= f.text_field :tipo %>
  </div>

  <div class="field">
    <%= f.label :valor %>
    <%= f.text_field :valor %>
  </div>

  <div class="field">
    <%= f.label :usuario_id %>
    <%= f.number_field :usuario_id %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/patrimonios/edit.html.erb
<h1>Editing Patrimonio</h1>

<%= render 'form', patrimonio: @patrimonio %>

<%= link_to 'Show', @patrimonio %> |
<%= link_to 'Back', patrimonios_path %>

app/views/patrimonios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Patrimonios</h1>

<table class="table table table-striped sortable">
  <thead>
    <tr>
      <th>Nome patrimonio</th>
      <th>Tipo</th>
      <th>Valor</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @patrimonios.each do |patrimonio| %>
      <tr>
        <td><%= patrimonio.nome_patrimonio %></td>
        <td><%= patrimonio.tipo %></td>
        <td><%= patrimonio.valor %></td>
        <td><%= patrimonio.usuario_id %></td>
        <td><%= link_to 'Show', patrimonio %></td>
        <td><%= link_to 'Edit', edit_patrimonio_path(patrimonio) %></td>
        <td><%= link_to 'Destroy', patrimonio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% link_to 'New Patrimonio', new_patrimonio_path %>

app/views/patrimonios/new.html.erb
<h1>New Patrimonio</h1>

<%= render 'form', patrimonio: @patrimonio %>

<%= link_to 'Back', patrimonios_path %>

app/views/patrimonios/show.html.erb
<h1>Patrimonio</h1>

<h2>
  <strong>Nome patrimonio:</strong>
  <%= @patrimonio.nome_patrimonio %>
</h2>

<p id="notice"><%= notice %></p>

<p>
  <strong>Tipo:</strong>
  <%= @patrimonio.tipo %>
</p>

<p>
  <strong>Valor:</strong>
  <%= @patrimonio.valor %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @patrimonio.usuario_id %>
</p>

<% link_to 'Edit', edit_patrimonio_path(@patrimonio) %> |
<%= link_to 'voltar', patrimonios_path %>

app/views/usuarios/_form.html.erb
<%= simple_form_for @usuario do |f| %>


  <div class="field">
    <%= f.input :nome %>
  </div>

  <div class="field">
    <%= f.input :sexo, collection: ["Homem", "Mulher"]%>
  </div>

  <div class="field">
    <%= f.input :idade %>
    </div>

  <div class="field">
    <%= f.input :endereco %>
    </div>

  <div class="field">
    <%= f.input :cidade %>
    </div>

  <div class="field_patrimonios">


    <%= link_to_add_association 'Novo Patrimonio', f, :patrimonios,
        'data-association-insertion-node' => '#patrimonios-usuario ol',
        'data-association-insertion-method' => 'append'
    %>

    <fieldset id="patrimonios-usuario">
      <ol>
        <%= f.fields_for :patrimonios do |patrimonio| %>
            <%= render partial: 'patrimonio_fields',  locals: {f: patrimonio}%>
        <%end%>
      </ol>
    </fieldset>

  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/_patrimonio_fields.html.erb
<li class="control-group nested-fields">
	
	<div class="controls">
		<%= f.input :nome_patrimonio%>
		<%= f.input :tipo%>
		<%= f.input :valor%>
	</div>
	
	<%= link_to_remove_association "remover", f%>

</li>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'voltar', @usuario %> 

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<%=form_tag(usuarios_path, method: :get) do %>
  <%= text_field_tag 'cidade', nil, placeholder: 'Busca por cidade'%>
  <%= submit_tag 'cidade'%>
  <%= text_field_tag 'valor', nil, placeholder: 'Busca por valor'%>
  <%= submit_tag 'valor'%>
<%end%>

<table class="table table table-striped sortable">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sexo</th>
      <th>Idade</th>
      <th>Endereco</th>
      <th>Cidade</th>
      <th>Patrimonios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.sexo %></td>
        <td><%= usuario.idade %></td>
        <td><%= usuario.endereco %></td>
        <td><%= usuario.cidade %></td>
        <td><%= usuario.patrimonios.sum(:valor) %></td>
        <td><%= link_to 'Show', usuario %></td>
        
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to "Inicio", root_path %>

<br>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form', usuario: @usuario %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<h1>Cidadão</h1>

<h2>
  <strong>Nome:</strong>
  <%= @usuario.nome %>
</h2>

<p id="notice"><%= notice %></p>

<p>
  <strong>Sexo:</strong>
  <%= @usuario.sexo %>
</p>

<p>
  <strong>Idade:</strong>
  <%= @usuario.idade %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @usuario.endereco %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @usuario.cidade %>
</p>


  <strong>Patrimonios:</strong>

  <table class="table table table-striped sortable">
  <thead>
    <tr>
      <th>Nome patrimonio</th>
      <th>Tipo</th>
      <th>Valor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuario.patrimonios.each do |patrimonio| %>
      <tr>
        <td><%= patrimonio.nome_patrimonio %></td>
        <td><%= patrimonio.tipo %></td>
        <td><%= patrimonio.valor %></td>
       </tr>
    <% end %>
  </tbody>
</table>

<%if usuario_signed_in? %>
  <%= link_to 'editar', edit_usuario_path(@usuario) %> 
  <%= link_to 'voltar', root_path %> 
<%elsif auditor_signed_in? %> 
  <%= link_to 'voltar', usuarios_path %> 
<%end%>

app/views/usuarios/usuarios_alto_valor.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sexo</th>
      <th>Idade</th>
      <th>Endereco</th>
      <th>Cidade</th>
      <th>Patrimonios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.sexo %></td>
        <td><%= usuario.idade %></td>
        <td><%= usuario.endereco %></td>
        <td><%= usuario.cidade %></td>
        <td><%= usuario.patrimonios.sum(:valor) %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/usuarios_cidade.erb
<p id="notice"><%= notice %></p>

<h1>Usuarios por cidade</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Sexo</th>
      <th>Idade</th>
      <th>Endereco</th>
      <th>Cidade</th>
      <th>Patrimonios</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nome %></td>
        <td><%= usuario.sexo %></td>
        <td><%= usuario.idade %></td>
        <td><%= usuario.endereco %></td>
        <td><%= usuario.cidade %></td>
        <td><%= usuario.patrimonios %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>